version: "3"

services:

  mysql:
    image: mysql:5.7
    ports:
    - "3306:3306"
    volumes:
    - ${MYSQL_VOLUME:-mysql-volume}:/var/lib/mysql:Z
    environment:
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DB}
    command:
    - "--character-set-server=utf8"
    - "--collation-server=utf8_unicode_ci"

  yourls:
    image: yourls
    restart: always
    depends_on:
    - mysql
    links:
    - mysql
    ports:
    - "3000:80"
    environment:
    - YOURLS_DB_USER=${MYSQL_USER}
    - YOURLS_DB_PASS=${MYSQL_PASSWORD}
    - YOURLS_DB_NAME=${MYSQL_DB}
    - YOURLS_DB_HOST=mysql
    - YOURLS_DEBUG=${YOURLS_DEBUG}
    - YOURLS_USER=${YOURLS_USER}
    - YOURLS_PASS=${YOURLS_PASS}
    - YOURLS_SITE=${YOURLS_SITE}
    - YOURLS_INDEX_WEBSITE=${YOURLS_INDEX_WEBSITE}

volumes:
  mysql-volume:
